CREATE TABLE EMPLOYEE (
Fname VARCHAR(50) NOT NULL,
Minit CHAR,
Lname VARCHAR(50) NOT NULL,
Ssn CHAR(9) NOT NULL,
Bdate DATE,
Address VARCHAR(100),
Sex CHAR NOT NULL,
Salary INT,
Super_ssn CHAR(9),
Dno INT NOT NULL,
PRIMARY KEY (Ssn),
FOREIGN KEY (Super_ssn) REFERENCES
EMPLOYEE (Ssn));

CREATE TABLE DEPARTMENT (
Dname VARCHAR(30) NOT NULL,
Dnumber INT NOT NULL,
Mgr_ssn CHAR(9) NOT NULL,
Mgr_start_date DATE,
PRIMARY KEY (Dnumber),
UNIQUE (Dname),
FOREIGN KEY (Mgr_ssn) REFERENCES
EMPLOYEE (Ssn));

CREATE TABLE DEPT_LOCATIONS (
Dnumber INT NOT NULL,
Dlocation VARCHAR(50) NOT NULL,
PRIMARY KEY(Dnumber, Dlocation),
FOREIGN KEY (Dnumber) REFERENCES
DEPARTMENT (Dnumber));

CREATE TABLE PROJECT (
Pname VARCHAR(30) NOT NULL,
Pnumber INT NOT NULL,
Plocation VARCHAR(50) NOT NULL,
Dnum INT NOT NULL,
PRIMARY KEY (Pnumber),
UNIQUE (Pname),
FOREIGN KEY (Dnum) REFERENCES
DEPARTMENT (Dnumber));

CREATE TABLE WORKS_ON (
Essn CHAR(9) NOT NULL,
Pno INT NOT NULL,
Hours DECIMAL(3,1),
PRIMARY KEY (Essn, Pno),
FOREIGN KEY (Essn) REFERENCES
EMPLOYEE (Ssn),
FOREIGN KEY (Pno) REFERENCES
PROJECT (Pnumber));

CREATE TABLE DEPENDENT (
Essn CHAR(9) NOT NULL,
Dependent_name VARCHAR(50) NOT NULL,
Sex CHAR NOT NULL,
Bdate DATE,
Relationship VARCHAR(15),
PRIMARY KEY (Essn, Dependent_name),
FOREIGN KEY (Essn) REFERENCES
EMPLOYEE (Ssn));

ALTER TABLE EMPLOYEE ADD CONSTRAINT FOREIGN KEY (Dno) 
REFERENCES DEPARTMENT (Dnumber);